version: '3.0'
services:
  fastapi:
    build: .
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - ./app/model_weight:/codebase/app/model_weight
